src: 
  host: 120.132.82.53
  username: back_local
  password: YeTBws8DWh4AfZij
  port: 3306

desc: 
  host: 192.168.101.239
  username: dev
  password: dev@2016
  port: 3306

columns:
  id: id
  check: update_time

syncJobCron: '*/10 * * * * ?'

oneQueryRows: 65536

syncConfigPath: /home/sync.js

logging:
  file: logs/application.log
  pattern:
    console: '%d[%-5level]%msg%n'
    file: '%d[%-5level]%msg%n'
  level:
    root: debug
    org.springframework: warn
    org.corefine.mysqlsync.Application: warn
