src: 
  host: 120.132.82.55
  username: rsync
  password: rsync
  port: 3307

desc: 
  host: 192.168.101.239
  username: dev
  password: dev@2016
  port: 3306

columns:
  id: id
  check: update_time

syncJobCron: '0 * * * * ?'

oneQueryRows: 1024

syncConfigPath: E:\\workspace3\\mysql-sync2\\src\\main\\resources\\sync.js

logging:
  file: logs/application.log
  pattern:
    console: '%d[%-5level]%msg%n'
    file: '%d[%-5level]%msg%n'
  level:
    root: debug
    org.springframework: warn
    org.corefine.mysqlsync.Application: warn
