src: 
  host: 192.168.101.180
  username: dev
  password: dev@2016
  port: 8066

desc: 
  host: 192.168.101.161
  username: dev
  password: dev@2016
  port: 3306


columns:
  id: id
  check: update_time

syncJobCron: '* * * * * ?'

oneQueryRows: 1024

syncConfigPath:  E://IdeaProjects//mysql-sync//src//main//resources//newToMycatsync.js

logging:
  file: logs/application.log
  pattern:
    console: '%d[%-5level]%msg%n'
    file: '%d[%-5level]%msg%n'
  level:
    root: debug
    org.springframework: warn
    org.corefine.mysqlsync.Application: warn
