src: 
  host: 192.168.10.53
  username: dev
  password: dev@2016
  port: 8066

desc: 
  host: 192.168.10.55
  username: dev
  password: dev@2016
  port: 3307


columns:
  id: id
  check: update_time

syncJobCron: '0 * * * * ?'

oneQueryRows: 1024

syncConfigPath:  /opt/newToMycatsync/newToMycatsync.js

logging:
  file: logs/application.log
  pattern:
    console: '%d[%-5level]%msg%n'
    file: '%d[%-5level]%msg%n'
  level:
    root: debug
    org.springframework: warn
    org.corefine.mysqlsync.Application: warn
